const _handleStateChange = ({ target }) => {
  return
  // target.value;
};

const formSeed = {
  group1: {
    groupHeader: "basic-information",
    q01: {
      placeholder: "Patient's Name",
      input: "",
      description: "Name",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q02: {
      placeholder: "",
      input: "date",
      description: "Today's Date",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q03: {
      placeholder: "",
      input: "date",
      description: "Date of Accident",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q04: {
      placeholder: "",
      input: "radio",
      selections: ["Yes", "No"],
      description:
        "Did this accident occur during the course of your employment or in a company vehicle?",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
  },

  group2: {
    groupHeader: "loaction-of-accident",
    q01: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q02: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q03: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q04: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q05: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q06: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q07: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
  },

  group3: {
    groupHeader: "vehicles-involved",
    q01: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q02: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
  },

  group4: {
    groupHeader: "your-location-inside-the-vehicle",
    q01: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q02: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q03: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q04: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q05: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q06: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q07: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q08: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q09: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q10: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
  },

  group5: {
    groupHeader: "at-the-time-of-impact",
    q01: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q02: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q03: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q04: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q05: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q06: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q07: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q08: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q09: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q10: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q11: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q12: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q13: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q14: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q15: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q16: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q17: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q18: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q19: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q20: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q21: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q22: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q23: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q24: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q25: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q26: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q27: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q28: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
  },

  group6: {
    groupHeader: "immediately-following-the-accident",
    q01: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q02: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q03: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q04: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q05: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q06: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q07: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
  },

  group7: {
    groupHeader: "your-work",
    q01: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q02: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q03: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q04: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q05: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q06: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q07: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
  },

  group8: {
    groupHeader: "before-and-after-the-accident",
    q01: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q02: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q03: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q04: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q05: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q06: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q07: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q08: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q09: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q10: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q11: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q12: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q13: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q14: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q15: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q16: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q17: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q18: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q19: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q20: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q21: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q22: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q23: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q24: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q25: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q26: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q27: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q28: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q29: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q30: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
    q31: {
      placeholder: "",
      input: "",
      description: "",
      id: "",
      onChange: { _handleStateChange },
      value: "",
    },
  },

  group9: {
    groupHeader: "signatures",
    patient01: {
      name: {
        placeholder: "",
        input: "",
        description: "",
        id: "",
        onChange: { _handleStateChange },
        value: "",
      },
      date: {
        placeholder: "",
        input: "",
        description: "",
        id: "",
        onChange: { _handleStateChange },
        value: "",
      },
      signature: {
        placeholder: "",
        input: "",
        description: "",
        id: "",
        onChange: { _handleStateChange },
        value: "",
      },
    },
    patient02: {
      name: {
        placeholder: "",
        input: "",
        description: "",
        id: "",
        onChange: { _handleStateChange },
        value: "",
      },
      date: {
        placeholder: "",
        input: "",
        description: "",
        id: "",
        onChange: { _handleStateChange },
        value: "",
      },
      signature: {
        placeholder: "",
        input: "",
        description: "",
        id: "",
        onChange: { _handleStateChange },
        value: "",
      },
    },
    attorney: {
      name: {
        placeholder: "",
        input: "",
        description: "",
        id: "",
        onChange: { _handleStateChange },
        value: "",
      },
      date: {
        placeholder: "",
        input: "",
        description: "",
        id: "",
        onChange: { _handleStateChange },
        value: "",
      },
      signature: {
        placeholder: "",
        input: "",
        description: "",
        id: "",
        onChange: { _handleStateChange },
        value: "",
      },
    },
  },
};

export default formSeed;
