const formSeed = {
  group1: {
    id: "basic-information",
    parentname: "group1",
    groupHeader: "basic-information",
    q01: {
      parentname: "q01",
      value: "",
      placeholder: "Patient's Name",
      input: "control",
      description: "Name",
      id: "patient-name",
    },
    q02: {
      parentname: "q02",
      value: "",
      placeholder: "",
      input: "date",
      description: "Today's Date",
      id: "",
    },
    q03: {
      parentname: "q03",
      value: "",
      placeholder: "",
      input: "date",
      description: "Date of Accident",
      id: "",
    },
    q04: {
      parentname: "q04",
      value: "",
      placeholder: "",
      input: "radio",
      selections: ["Yes", "No"],
      description:
        "Did this accident occur during the course of your employment or in a company vehicle?",
      id: "",
    },
  },

  group2: {
    parentname: "group2",
    groupHeader: "loaction-of-accident",
    q01: {
      parentname: "q01",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q02: {
      parentname: "q02",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q03: {
      parentname: "q03",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q04: {
      parentname: "q04",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q05: {
      parentname: "q05",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q06: {
      parentname: "q06",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q07: {
      parentname: "q07",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
  },

  group3: {
    parentname: "group3",
    groupHeader: "vehicles-involved",
    q01: {
      parentname: "q01",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q02: {
      parentname: "q02",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
  },

  group4: {
    parentname: "group4",
    groupHeader: "your-location-inside-the-vehicle",
    q01: {
      parentname: "q01",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q02: {
      parentname: "q02",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q03: {
      parentname: "q03",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q04: {
      parentname: "q04",
      value: "",
      placeholder: "",
      input: "", //SCSS Tag Group:
      description: "",
      id: "",
    },
    q05: {
      parentname: "q05",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q06: {
      parentname: "q06",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q07: {
      parentname: "q07",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q08: {
      parentname: "q08",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q09: {
      parentname: "q09",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q10: {
      parentname: "q10",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
  },

  group5: {
    parentname: "group5",
    groupHeader: "at-the-time-of-impact",
    q01: {
      parentname: "q01",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q02: {
      parentname: "q02",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q03: {
      parentname: "q03",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q04: {
      parentname: "q04",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q05: {
      parentname: "q05",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q06: {
      parentname: "q06",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q07: {
      parentname: "q07",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q08: {
      parentname: "q08",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q09: {
      parentname: "q09",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q10: {
      parentname: "q10",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q11: {
      parentname: "q11",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q12: {
      parentname: "q12",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q13: {
      parentname: "q13",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q14: {
      parentname: "q14",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q15: {
      parentname: "q15",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q16: {
      parentname: "q16",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q17: {
      parentname: "q17",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q18: {
      parentname: "q18",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q19: {
      parentname: "q19",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q20: {
      parentname: "q20",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q21: {
      parentname: "q21",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q22: {
      parentname: "q22",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q23: {
      parentname: "q23",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q24: {
      parentname: "q24",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q25: {
      parentname: "q25",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q26: {
      parentname: "q26",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q27: {
      parentname: "q27",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q28: {
      parentname: "q28",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
  },

  group6: {
    parentname: "group6",
    groupHeader: "immediately-following-the-accident",
    q01: {
      parentname: "q01",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q02: {
      parentname: "q02",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q03: {
      parentname: "q03",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q04: {
      parentname: "q04",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q05: {
      parentname: "q05",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q06: {
      parentname: "q06",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q07: {
      parentname: "q07",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
  },

  group7: {
    parentname: "group7",
    groupHeader: "your-work",
    q01: {
      parentname: "q01",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q02: {
      parentname: "q02",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q03: {
      parentname: "q03",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q04: {
      parentname: "q04",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q05: {
      parentname: "q05",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q06: {
      parentname: "q06",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q07: {
      parentname: "q07",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
  },

  group8: {
    parentname: "group8",
    groupHeader: "before-and-after-the-accident",
    q01: {
      parentname: "q01",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q02: {
      parentname: "q02",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q03: {
      parentname: "q03",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q04: {
      parentname: "q04",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q05: {
      parentname: "q05",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q06: {
      parentname: "q06",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q07: {
      parentname: "q07",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q08: {
      parentname: "q08",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q09: {
      parentname: "q09",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q10: {
      parentname: "q10",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q11: {
      parentname: "q11",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q12: {
      parentname: "q12",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q13: {
      parentname: "q13",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q14: {
      parentname: "q14",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q15: {
      parentname: "q15",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q16: {
      parentname: "q16",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q17: {
      parentname: "q17",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q18: {
      parentname: "q18",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q19: {
      parentname: "q19",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q20: {
      parentname: "q20",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q21: {
      parentname: "q21",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q22: {
      parentname: "q22",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q23: {
      parentname: "q23",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q24: {
      parentname: "q24",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q25: {
      parentname: "q25",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q26: {
      parentname: "q26",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q27: {
      parentname: "q27",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q28: {
      parentname: "q28",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q29: {
      parentname: "q29",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q30: {
      parentname: "q30",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
    q31: {
      parentname: "q31",
      value: "",
      placeholder: "",
      input: "",
      description: "",
      id: "",
    },
  },
};

export default formSeed;
